{
 "title": "Docker Container Dashboard",
 "description": "Dashboard with details of the container metrics and host OS metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datacenter", "label": "datacenter", "query": "${VAR_DATACENTER}" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(cadvisor_version_info, env)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cadvisor_version_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cadvisor_version_info{env=~\"$environment\",job=~\"$job\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,3m,5m,10m,30m" },
   {
    "name": "id",
    "label": "ID",
    "query": {
     "query": "label_values(container_memory_usage_bytes{name=~\"$containers\", instance=~\"$node\"}, id)"
    }
   },
   {
    "name": "containers",
    "label": "Containers",
    "query": {
     "query": "label_values(container_memory_usage_bytes{instance=~\"$node\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id=~\"/docker/.*\",instance=~\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$node\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$node\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$containers\",instance=~\"$node\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"$containers\",instance=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$containers\",instance=~\"$node\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$containers\",instance=~\"$node\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name=~\"$containers\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"$containers\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Available Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name=~\"$containers\",instance=~\"$node\"}-container_memory_usage_bytes{name!=\"\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\",instance=~\"$node\"}) by (name, id)"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{name!=\"\",instance=~\"$node\"}) by (name, id)"
    }
   ]
  }
 ]
}